import { m } from '@/paraglide/messages.js';
import type { PromptExample } from '@/components/prompt-gallery';

export function expandedPromptExamples(): PromptExample[] {
  return [
    {
      id: 'moon-laundromat',
      title: m['studio.library.moon_laundromat.title'](),
      category: 'surreal',
      image: '/imgs/original/moon-laundromat.webp',
      alt: m['studio.library.moon_laundromat.title'](),
      prompt: m['studio.library.moon_laundromat.prompt'](),
      mode: 'generate',
    },
    {
      id: 'sunlit-potter',
      title: m['studio.library.sunlit_potter.title'](),
      category: 'portrait',
      image: '/imgs/original/sunlit-potter.webp',
      alt: m['studio.library.sunlit_potter.title'](),
      prompt: m['studio.library.sunlit_potter.prompt'](),
      mode: 'generate',
    },
    {
      id: 'citrus-tart',
      title: m['studio.library.citrus_tart.title'](),
      category: 'food',
      image: '/imgs/original/citrus-tart.webp',
      alt: m['studio.library.citrus_tart.title'](),
      prompt: m['studio.library.citrus_tart.prompt'](),
      mode: 'generate',
    },
    {
      id: 'amber-skincare',
      title: m['studio.library.amber_skincare.title'](),
      category: 'product',
      image: '/imgs/original/amber-skincare.webp',
      alt: m['studio.library.amber_skincare.title'](),
      prompt: m['studio.library.amber_skincare.prompt'](),
      mode: 'generate',
    },
    {
      id: 'panda-bakery',
      title: m['studio.library.panda_bakery.title'](),
      category: 'illustration',
      image: '/imgs/original/panda-bakery.webp',
      alt: m['studio.library.panda_bakery.title'](),
      prompt: m['studio.library.panda_bakery.prompt'](),
      mode: 'generate',
    },
    {
      id: 'red-panda-boba',
      title: m['studio.library.red_panda_boba.title'](),
      category: 'sticker',
      image: '/imgs/original/red-panda-boba.webp',
      alt: m['studio.library.red_panda_boba.title'](),
      prompt: m['studio.library.red_panda_boba.prompt'](),
      mode: 'transparent',
    },
    {
      id: 'whale-greenhouse',
      title: m['studio.library.whale_greenhouse.title'](),
      category: 'surreal',
      image: '/imgs/original/whale-greenhouse.webp',
      alt: m['studio.library.whale_greenhouse.title'](),
      prompt: m['studio.library.whale_greenhouse.prompt'](),
      mode: 'generate',
    },
    {
      id: 'rooftop-musician',
      title: m['studio.library.rooftop_musician.title'](),
      category: 'portrait',
      image: '/imgs/original/rooftop-musician.webp',
      alt: m['studio.library.rooftop_musician.title'](),
      prompt: m['studio.library.rooftop_musician.prompt'](),
      mode: 'generate',
    },
    {
      id: 'galaxy-donut',
      title: m['studio.library.galaxy_donut.title'](),
      category: 'food',
      image: '/imgs/original/galaxy-donut.webp',
      alt: m['studio.library.galaxy_donut.title'](),
      prompt: m['studio.library.galaxy_donut.prompt'](),
      mode: 'generate',
    },
    {
      id: 'mint-headphones',
      title: m['studio.library.mint_headphones.title'](),
      category: 'product',
      image: '/imgs/original/mint-headphones.webp',
      alt: m['studio.library.mint_headphones.title'](),
      prompt: m['studio.library.mint_headphones.prompt'](),
      mode: 'generate',
    },
    {
      id: 'rabbit-moon-garden',
      title: m['studio.library.rabbit_moon_garden.title'](),
      category: 'illustration',
      image: '/imgs/original/rabbit-moon-garden.webp',
      alt: m['studio.library.rabbit_moon_garden.title'](),
      prompt: m['studio.library.rabbit_moon_garden.prompt'](),
      mode: 'generate',
    },
    {
      id: 'duck-raincoat',
      title: m['studio.library.duck_raincoat.title'](),
      category: 'sticker',
      image: '/imgs/original/duck-raincoat.webp',
      alt: m['studio.library.duck_raincoat.title'](),
      prompt: m['studio.library.duck_raincoat.prompt'](),
      mode: 'transparent',
    },
    {
      id: 'teacup-waterfall',
      title: m['studio.library.teacup_waterfall.title'](),
      category: 'surreal',
      image: '/imgs/original/teacup-waterfall.webp',
      alt: m['studio.library.teacup_waterfall.title'](),
      prompt: m['studio.library.teacup_waterfall.prompt'](),
      mode: 'generate',
    },
    {
      id: 'mountain-hiker',
      title: m['studio.library.mountain_hiker.title'](),
      category: 'portrait',
      image: '/imgs/original/mountain-hiker.webp',
      alt: m['studio.library.mountain_hiker.title'](),
      prompt: m['studio.library.mountain_hiker.prompt'](),
      mode: 'generate',
    },
    {
      id: 'pistachio-croissant',
      title: m['studio.library.pistachio_croissant.title'](),
      category: 'food',
      image: '/imgs/original/pistachio-croissant.webp',
      alt: m['studio.library.pistachio_croissant.title'](),
      prompt: m['studio.library.pistachio_croissant.prompt'](),
      mode: 'generate',
    },
    {
      id: 'opal-watch',
      title: m['studio.library.opal_watch.title'](),
      category: 'product',
      image: '/imgs/original/opal-watch.webp',
      alt: m['studio.library.opal_watch.title'](),
      prompt: m['studio.library.opal_watch.prompt'](),
      mode: 'generate',
    },
    {
      id: 'capybara-spa',
      title: m['studio.library.capybara_spa.title'](),
      category: 'illustration',
      image: '/imgs/original/capybara-spa.webp',
      alt: m['studio.library.capybara_spa.title'](),
      prompt: m['studio.library.capybara_spa.prompt'](),
      mode: 'generate',
    },
    {
      id: 'corgi-chef',
      title: m['studio.library.corgi_chef.title'](),
      category: 'sticker',
      image: '/imgs/original/corgi-chef.webp',
      alt: m['studio.library.corgi_chef.title'](),
      prompt: m['studio.library.corgi_chef.prompt'](),
      mode: 'transparent',
    },
    {
      id: 'jellyfish-tram',
      title: m['studio.library.jellyfish_tram.title'](),
      category: 'surreal',
      image: '/imgs/original/jellyfish-tram.webp',
      alt: m['studio.library.jellyfish_tram.title'](),
      prompt: m['studio.library.jellyfish_tram.prompt'](),
      mode: 'generate',
    },
    {
      id: 'bookshop-reader',
      title: m['studio.library.bookshop_reader.title'](),
      category: 'portrait',
      image: '/imgs/original/bookshop-reader.webp',
      alt: m['studio.library.bookshop_reader.title'](),
      prompt: m['studio.library.bookshop_reader.prompt'](),
      mode: 'generate',
    },
    {
      id: 'peach-soda',
      title: m['studio.library.peach_soda.title'](),
      category: 'food',
      image: '/imgs/original/peach-soda.webp',
      alt: m['studio.library.peach_soda.title'](),
      prompt: m['studio.library.peach_soda.prompt'](),
      mode: 'generate',
    },
    {
      id: 'ceramic-lamp',
      title: m['studio.library.ceramic_lamp.title'](),
      category: 'product',
      image: '/imgs/original/ceramic-lamp.webp',
      alt: m['studio.library.ceramic_lamp.title'](),
      prompt: m['studio.library.ceramic_lamp.prompt'](),
      mode: 'generate',
    },
    {
      id: 'turtle-airship',
      title: m['studio.library.turtle_airship.title'](),
      category: 'illustration',
      image: '/imgs/original/turtle-airship.webp',
      alt: m['studio.library.turtle_airship.title'](),
      prompt: m['studio.library.turtle_airship.prompt'](),
      mode: 'generate',
    },
    {
      id: 'penguin-skater',
      title: m['studio.library.penguin_skater.title'](),
      category: 'sticker',
      image: '/imgs/original/penguin-skater.webp',
      alt: m['studio.library.penguin_skater.title'](),
      prompt: m['studio.library.penguin_skater.prompt'](),
      mode: 'transparent',
    },
    {
      id: 'desert-door',
      title: m['studio.library.desert_door.title'](),
      category: 'surreal',
      image: '/imgs/original/desert-door.webp',
      alt: m['studio.library.desert_door.title'](),
      prompt: m['studio.library.desert_door.prompt'](),
      mode: 'generate',
    },
    {
      id: 'botanical-fashion',
      title: m['studio.library.botanical_fashion.title'](),
      category: 'portrait',
      image: '/imgs/original/botanical-fashion.webp',
      alt: m['studio.library.botanical_fashion.title'](),
      prompt: m['studio.library.botanical_fashion.prompt'](),
      mode: 'generate',
    },
    {
      id: 'sushi-garden',
      title: m['studio.library.sushi_garden.title'](),
      category: 'food',
      image: '/imgs/original/sushi-garden.webp',
      alt: m['studio.library.sushi_garden.title'](),
      prompt: m['studio.library.sushi_garden.prompt'](),
      mode: 'generate',
    },
    {
      id: 'violet-sneaker',
      title: m['studio.library.violet_sneaker.title'](),
      category: 'product',
      image: '/imgs/original/violet-sneaker.webp',
      alt: m['studio.library.violet_sneaker.title'](),
      prompt: m['studio.library.violet_sneaker.prompt'](),
      mode: 'generate',
    },
    {
      id: 'bear-stargazer',
      title: m['studio.library.bear_stargazer.title'](),
      category: 'illustration',
      image: '/imgs/original/bear-stargazer.webp',
      alt: m['studio.library.bear_stargazer.title'](),
      prompt: m['studio.library.bear_stargazer.prompt'](),
      mode: 'generate',
    },
    {
      id: 'frog-camera',
      title: m['studio.library.frog_camera.title'](),
      category: 'sticker',
      image: '/imgs/original/frog-camera.webp',
      alt: m['studio.library.frog_camera.title'](),
      prompt: m['studio.library.frog_camera.prompt'](),
      mode: 'transparent',
    },
  ];
}

export function promptExamples(): PromptExample[] {
  return [
    ...expandedPromptExamples(),
    {
      id: 'space-cat',
      title: m['studio.example.product'](),
      category: 'surreal',
      image: '/imgs/original/space-cat-koi.webp',
      alt: m['studio.carousel.product_alt'](),
      prompt: m['studio.prompt.product'](),
      mode: 'generate',
    },
    {
      id: 'cloud-house',
      title: m['studio.library.cloud_house.title'](),
      category: 'surreal',
      image: '/imgs/original/cloud-house.webp',
      alt: m['studio.library.cloud_house.title'](),
      prompt: m['studio.library.cloud_house.prompt'](),
      mode: 'generate',
    },
    {
      id: 'rain-portrait',
      title: m['studio.library.rain_portrait.title'](),
      category: 'portrait',
      image: '/imgs/original/rain-portrait.webp',
      alt: m['studio.library.rain_portrait.title'](),
      prompt: m['studio.library.rain_portrait.prompt'](),
      mode: 'generate',
    },
    {
      id: 'ramen-city',
      title: m['studio.example.editorial'](),
      category: 'surreal',
      image: '/imgs/original/ramen-miniature-city.webp',
      alt: m['studio.carousel.editorial_alt'](),
      prompt: m['studio.prompt.editorial'](),
      mode: 'generate',
    },
    {
      id: 'matcha-dessert',
      title: m['studio.library.matcha_dessert.title'](),
      category: 'food',
      image: '/imgs/original/matcha-dessert.webp',
      alt: m['studio.library.matcha_dessert.title'](),
      prompt: m['studio.library.matcha_dessert.prompt'](),
      mode: 'generate',
    },
    {
      id: 'fox-library',
      title: m['studio.library.fox_library.title'](),
      category: 'illustration',
      image: '/imgs/original/fox-library.webp',
      alt: m['studio.library.fox_library.title'](),
      prompt: m['studio.library.fox_library.prompt'](),
      mode: 'generate',
    },
    {
      id: 'chrome-sneaker',
      title: m['studio.library.chrome_sneaker.title'](),
      category: 'product',
      image: '/imgs/original/chrome-sneaker.webp',
      alt: m['studio.library.chrome_sneaker.title'](),
      prompt: m['studio.library.chrome_sneaker.prompt'](),
      mode: 'generate',
    },
    {
      id: 'otter-sticker',
      title: m['studio.example.sticker'](),
      category: 'sticker',
      image: '/imgs/original/astronaut-otter-sticker.webp',
      alt: m['studio.carousel.sticker_alt'](),
      prompt: m['studio.prompt.sticker'](),
      mode: 'transparent',
    },
    {
      id: 'perfume',
      title: m['studio.library.perfume.title'](),
      category: 'product',
      image: '/imgs/original/perfume-product.webp',
      alt: m['studio.library.perfume.title'](),
      prompt: m['studio.library.perfume.prompt'](),
      mode: 'generate',
    },
  ];
}
